### ISSUE TITLE
Kick on bot

### ISSUE THREAD

**Issue by DavidVerdier** [Discutea/DiscuteaServices#6]
The bots do not join the channel when they are kicked.

**Comment by JudgeDT** [comment]
Pour "ajouter" à la chose : penser à ajouter le robot dans les ulines d'Anope (en plus de l'IRCd), afin que Anope laisse le robot tranquille et ne le kick plus inutilement sur les canaux.

Rajoutons que lorsque le robot se fait kicker et reviens, il ne récupère pas ses modes sur le canal.
